feat(baseservice): adds BaseService class and ServiceClient protocol
watson-developer-cloud/restkit pull request #31
Opened 2019-09-11 19:43 UTC by repjarms

this adds some compiler time checks for the minimum properties we expect service clients to use

### Summary

This update adds two entities of note:

1. `BaseService` class - the super class we will use for all client service classes
2. `ClientService` protocol - the interface that all client service classes will conform to

This provides us with better compile-time enforcement of what properties we expect from each service class (Watson and beyond), as well as less property duplication for properties that are used across every service client currently.

For Watson specifically, this will require generator changes, we will remove a lot of class specific properties, and the main init method will look like this:

```swift
    public init(version: String, authenticator: Authenticator) {
        self.version = version
        RestRequest.userAgent = Shared.userAgent
        super.init(authenticator: authenticator)
    }
```

Where the `BaseService` constructor called would set:

```swift
    public init(authenticator: Authenticator) {
        self.authenticator = authenticator
        self.defaultHeaders = [String : String]()
        self.session = URLSession(configuration: URLSessionConfiguration.default)
    }
```

I will comment on the generator with specific changes to the templates, but I included that example just for context.

2019-09-12 15:29 UTC, padamstx approved these changes
I'm not a swift expert (and I don't play one on TV), but this looks fine to me :)

2019-09-13 00:54 UTC, mkistler requested changes
This feels like a halfway step that doesn't add much value. I think you should add a `request` method to the base service that uses the authenticator, defaultHeaders, and session properties you have here (and maybe add the UserAgent) to simplify the request interface from the SDKs.

2019-09-13 13:49 UTC, repjarms commented
@mkistler a common `request` method would be good, but it's not immediately clear looking at the Swift SDK how we could standardize such a request. Each method for each service class has a lot of unique headers, query params, and URL params... Trying to create a base method that could be used might end up being too overloaded.

2019-09-13 14:44 UTC, repjarms commented
I'm going to put this PR on hold until after the upcoming release since this is not a breaking change and may require some more design work.

2019-09-13 14:44 UTC, closed without merging